#!/bin/sh
[ -f /etc/default/aptitude-robot ] && . /etc/default/aptitude-robot

# delay execution for a random number of seconds
# analogous to the daily cron of apt and cron-apt
if [ "$1" = "--random-delay" ]; then
    if [ "$MAX_RANDOM_DELAY_SECONDS" -gt 0 ] ; then
        if [ -z "$RANDOM" ] ; then
            # A fix for shells that do not have this bash feature.
            RANDOM=$(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -c"1-5")
        fi
        DELAY=$(($RANDOM % $MAX_RANDOM_DELAY_SECONDS))
        sleep $DELAY
    fi
fi

if [ ! -x /usr/sbin/aptitude-robot ]; then
    exit   # aptitude-robot has been deinstalled but not purged
fi

if [ -n "$LOG_SESSION" ] ; then
    LOG_SESSION="$LOG_SESSION".$$
    touch "$LOG_SESSION"
    if [ -f "$LOG_SESSION" ]; then
        exec 1>"$LOG_SESSION" 2>&1
    fi
fi

cleanup () {
    echo "aptitude-robot ended at" `date --rfc-3339=seconds`
    echo ""
    if [ -n "$LOG_SESSION" -a -f "$LOG_SESSION" ]; then
        if [ -n "$LOGFILE" ]; then
            touch "$LOGFILE"   # create the log file if necessary
            if [ -f "$LOGFILE" ]; then
                cat "$LOG_SESSION" >> "$LOGFILE"
            fi
        fi
        if [ -n "$MAIL_TO" ]; then
            mail -s "aptitude-robot report on `hostname`" $MAIL_TO < "$LOG_SESSION"
        fi
        rm "$LOG_SESSION"
    fi
}
trap cleanup INT TERM QUIT HUP EXIT
set -e

echo "aptitude-robot started at" `date --rfc-3339=seconds`

DEBCONF_FRONTEND=noninteractive
export DEBCONF_FRONTEND
/usr/bin/aptitude update
# yes "" forces the default answer to any configuration question
nice yes "" | /usr/sbin/aptitude-robot
